# -*- coding: utf-8 -*-
"""Paddle OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j-tfcKjW5BOUNMAKoaPQxhvNfIvPSs-m

# **1. Install and Import Dependencies**
"""
"""
# Github repo installation 
!pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple

# Install paddle OCR
!pip install paddleocr

# Clonde paddle OCR repo for fonts
!git clone https://github.com/PaddlePaddle/PaddleOCR

# get Images
!wget https://github.com/nicknochnack/DrugLabelExtraction-/raw/main/drug1.jpg
!wget https://github.com/nicknochnack/DrugLabelExtraction-/raw/main/drug2.jpg
!wget https://github.com/nicknochnack/DrugLabelExtraction-/raw/main/drug3.jpg
"""
"""# **2. Instantiate Model and Detect**

"""

from paddleocr import PaddleOCR, draw_ocr
from matplotlib import pyplot as plt
import cv2
import os

# setup model
ocr = PaddleOCR(lang="en")

img_path = os.path.join(".", "drug3.jpg")

img_path

result = ocr.ocr(img_path)

result

for res in result:
    print(res[1][0])



"""# **3. Visualise Result**

"""

# extracting detected components
boxes = [res[0] for res in result]
texts = [res[1][0] for res in result]
scores = [res[1][1] for res in result]

# Specifying font path ofr draw_ocr
font_path = os.path.join("PaddleOCR", "doc", "fonts", "latin.ttf")

# Import our image - drug 1/2/3
img = cv2.imread(img_path) # Import image
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # reorders color channels

# visualize or image and detection
plt.figure(figsize=(15, 15)) # resize display area
annotated = draw_ocr(img, boxes, texts, scores, font_path=font_path) # draw annotations on image
plt.imshow(annotated) # Show the image

